### ISSUE TITLE
未来篇 熵宇宙的终极规则 有句话可能有问题

### ISSUE THREAD

**Issue by nuoqish** [ruanyf/survivor#14]
在未来篇 熵：宇宙的终极规则中，有句话是这样的：

> 转换的能量越大，创造出来的新状态就会越多，因此高能量系统不如低能量系统稳定，因为前者的熵较大。

高能量的系统应该是熵较小才对吧？

因为既然都是熵增的过程，熵是能量释放的一部分，高能量系统之所以不稳定，是它想要释放能量增加熵，从而达到低能量高熵的结果。

**Comment by ruanyf** [comment]
谢谢指出。原文表达不正确，我改了一下。
