### ISSUE TITLE
有句话语义感觉不太对，像是与要表达的相反

### ISSUE THREAD

**Issue by jingyoushihang** [ruanyf/survivor#18]
方法篇 -> 为什么起床后不能收邮件？ -> 5.寻找借口 -> "最后一句话"

如果你有不得不做的事情，那就去做它，而且通过查看邮件拖延它。
最后一句应该是“而不是”吧
![image](https://github.com/ruanyf/survivor/assets/67270162/722bd9e1-2f03-4108-85d2-efe009535ea5)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
